### ISSUE TITLE
GRPC server not ready to accept requests

### ISSUE THREAD

**Issue by tjwoon** [kubemq-io/kubemq-node#13]
I get a GRPC error quite frequently, when trying to push messages onto a queue.

Code:

```javascript
const KUBEMQ_ADDRESS = 'kubemq-cluster-grpc.kubemq.svc.cluster.local:50000'
const CHANNEL_NAME = 'someChannel'
const queue = new kubemq.MessageQueue(KUBEMQ_ADDRESS, CHANNEL_NAME, 'transaction')
await queue.sendQueueMessage(new kubemq.Message(
  'message',
  kubemq.stringToByte(JSON.stringify({
    ... some contents ...
  })),
  []
))
```
The `sendQueueMessage` method throws this: `Error: Error: 14 UNAVAILABLE: grpc server is not ready to accept requests.`

It doesn't happen all the time.

Log from the KubeMQ cluster node: `{"level":"WARN","time":"2020-07-31T03:35:49.771Z","msg":"grpc interface is not accepting traffic, waiting for broker","host":"kubemq-cluster-1","module":"grpc"}`

I'm running KubeMQ on s plain Digital Ocean Kubernetes cluster, with 2 worker nodes (1 vCPU, 2GB per node).

```
$ kubectl get pods -n kubemq
NAME                                READY   STATUS    RESTARTS   AGE
kubemq-cluster-0                    1/1     Running   0          23m
kubemq-cluster-1                    1/1     Running   0          23m
kubemq-cluster-2                    1/1     Running   0          23m
kubemq-dashboard-5bbb8cbbb5-pmx76   2/2     Running   0          19d
kubemq-operator-5595cfb695-pd7dk    1/1     Running   0          19d
```

**Comment by kubemq** [comment]
Until you will form a cluster 3/3, you will not be able to send or receive messages from the nodes.

**Comment by tjwoon** [comment]
Hi @kubemq - I have 3 kubemq-cluster nodes. And sometimes I am able to send/receive messages; sometimes I get this error.

Do you mean all these 3 nodes must be connected?
How will I know if they are connected?
Why would they become disconnected so frequently?

**Comment by kubemq** [comment]
3 nodes needs be connected to each other to form a healthy cluster.
if the cluster is healthy, you can send and receive messages. if not, you will get an error like above.
if for some reason you have network issues or any other resources limitations, you might have connection issue.
