### ISSUE TITLE
[Feature Request] Node Red node

### ISSUE THREAD

**Issue by rjbaat** [kubemq-io/kubemq-node#15]
Hi all, 

I would love to use KubeMQ in my project but I am using Node Red (based on NodeJS) to route the data.
I noticed there is no Node Red node for KubeMQ as SDK just yet.

Is it possible you guys create a Node Red node from the NodeJS SDK?
This is not something i am able to do myself unfortunately.

Would be awesome!
Best Regards!

**Comment by eitam-ring** [comment]
Hi @rjbaat ,
We will take a look at it , and will update you as soon as we can

**Comment by rjbaat** [comment]
Thnx alot! Would be very helpful!

**Comment by rjbaat** [comment]
@eitam-ring do you have any news on this? :)

**Comment by eitam-ring** [comment]
hi @rjbaat 
We didn't forgot, but still didn't reach that.

**Comment by rjbaat** [comment]
Oke thnx. Looking forward to it!

**Comment by kubemq** [comment]
Please check our new SDk at : [https://github.com/kubemq-io/kubemq-js](https://github.com/kubemq-io/kubemq-js)
