### ISSUE TITLE
Imports in RPC broken

### ISSUE THREAD

**Issue by Vetm** [kubemq-io/kubemq-node#17]
In the currently published NPM package some imports are broken.

In the git repo you have the folders `rpc/lowLevel` and `rpc/lowlevel`. However, the installed version in my node_modules is missing the `lowlevel` folder. It looks like these folders have been merged there. This causes some imports to break in the following files:
- querySender.jsL24
- commandReceiver.jsL24
- commandSender.jsL27

**Comment by eitam-ring** [comment]
Hi @Vetm ,
Thanks for the notice will look into it and fix it

**Comment by eitam-ring** [comment]
Hi @Vetm ,
We removed the old lowlevel , now only - **lowLevel** exists
Please look at version 1.0.7 at NPM
Again, thank you for the notice.

**Comment by eitam-ring** [comment]
Hey,
Closing since the issue was fixed ,
If you encounter a similar issue or a new one please open a new issue
