### ISSUE TITLE
[Feature Request] TypeScript typings

### ISSUE THREAD

**Issue by Vetm** [kubemq-io/kubemq-node#18]
It would be great if you could add typings so we can make use of intellisense while using typescript.

**Comment by eitam-ring** [comment]
@Vetm hi,
We will take a look at it , and will update you as soon as we can

**Comment by kubemq** [comment]
Please check our new SDk at : [https://github.com/kubemq-io/kubemq-js](https://github.com/kubemq-io/kubemq-js)
