### ISSUE TITLE
Authentication example

### ISSUE THREAD

**Issue by virus2016** [kubemq-io/kubemq-node#19]
Hi there,

I am wondering if you have an example of connecting to KubeMQ with authentication?

Thanks,

**Comment by eitam-ring** [comment]
Hi @virus2016 ,
We are working on a fully working example of authentication mode sdk, 
we will release the version here when its ready and update you

**Comment by eitam-ring** [comment]
Hey @virus2016 
Added examples for authentication use
please use version 2.1.1 for authentication

**Comment by virus2016** [comment]
Thank you @eitam-ring!

**Comment by eitam-ring** [comment]
Closing since the issue been resolved ,
If further assistance is needed feel free to open an issue.
