### ISSUE TITLE
Inconsistency in codebase

### ISSUE THREAD

**Issue by Woody88** [kubemq-io/kubemq-node#21]
Hello, 

I am interested in using kubemq so I decided to look at this package and noticed some possible problems in the codebase. 

Here
https://github.com/kubemq-io/kubemq-node/blob/bebd4c363b9566ebcc5d9b15fa7eb645b4e400d4/rpc/lowLevel/queryResponse.js#L35-L43

and here 
https://github.com/kubemq-io/kubemq-node/blob/bebd4c363b9566ebcc5d9b15fa7eb645b4e400d4/rpc/lowLevel/responder.js#L56-L60

Also, there it doesn't seem like the shape(types) of the objects are consistent between the other SDKs(go, java, etc..), and lastly some of the data object output extra fields when actually executing. For instance, Query request and response will have an extra property like "Span".

What is the roadmap for this SDK?

**Comment by eitam-ring** [comment]
Hi @Woody88 ,
Thank you for sharing we will look into it ,
As well will keep you updated regarding to road map

**Comment by kubemq** [comment]
Please check our new SDk at : [https://github.com/kubemq-io/kubemq-js](https://github.com/kubemq-io/kubemq-js)
