### ISSUE TITLE
Command with response payload

### ISSUE THREAD

**Issue by jgrenon** [kubemq-io/kubemq-node#7]
I've reviewed your samples and I haven't found any showing how to return a response payload from a command. You only set the Timestamp, but there nothing returned. Could you provide one? Right now, I've tried many things like setting the Body of the CommandReceiver.Response, but nothing is brought back to the sender. 
Also, how do you set "At Most Once" when sending a command? Right now, all my replicas get the command...

**Comment by eitam-ring** [comment]
Hi @jgrenon ,
Command is part of RPC Model.
RPC Contain Command and Querry, Command Is not supposed to return the body

> Commands implement the synchronous messaging pattern in which the sender sends a request and waits for a specific amount of time to get a response.
> The response can be successful or not. This is the responsibility of the responder to return with the result of the command within the time the sender set in the request.
> 
> 

You want to use Query if the body is needed 


>  Queries implement the synchronous messaging pattern in which the sender sends a request and waits for a specific amount of time to get a response.
>  
>  The response must include metadata or body together with an indication of successful or not operation. This is the responsibility of the responder to return with the result of the query within the time the sender set in the request.
> 

Regarding the second issue.
If you want a multi sub that return response please use our grouping feature:

> Group: Optional parameter when subscribing to a channel. A set of subscribers can define the same group so that only one of the subscribers within the group will receive a specific event. Used mainly for load balancing. Subscribing without the group parameter ensures receiving all the channel messages. (When using Grouping all the programs that are assigned to the group need to have to same channel name)
