### ISSUE TITLE
Does kubemq support sharding?

### ISSUE THREAD

**Issue by dilipkumar2k6** [kubemq-io/kubemq-node#8]
I have a requirement to support the message with 1TB. Therefore I don't want to have one big node; instead sharded cluster with smaller storage. 
Is it possible? I don't see it in the documentation.

**Comment by eitam-ring** [comment]
hi @dilipkumar2k6 
In this case, sounds like sharding won't be the solution,
Maybe you can consider slicing it to parts and reassemble it at the receiver side?
